apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "automate-e.fullname" . }}-character
  labels:
    {{- include "automate-e.labels" . | nindent 4 }}
data:
  character.json: |
    {{- .Values.character | toJson | nindent 4 }}
