{{- if .Values.dashboard.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "automate-e.fullname" . }}
  labels:
    {{- include "automate-e.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "automate-e.selectorLabels" . | nindent 4 }}
    {{- if eq .Values.mode "split" }}
    app.kubernetes.io/component: gateway
    {{- end }}
  ports:
    - name: dashboard
      port: {{ .Values.dashboard.port }}
      targetPort: {{ .Values.dashboard.port }}
{{- end }}
